apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }} # .Release.Name değişkeni, Helm chart'ın adını temsil eder.
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" # .Values.image.repository ve .Values.image.tag değişkenleri, Helm chart'ın values.yaml dosyasında tanımlanmış olan değerlerdir.
        ports:
        - containerPort: 80 