apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc
spec:
  storageClassName: demo-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc-2
spec:
  storageClassName: ""
  volumeName: demo-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
