apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-web-index
  namespace: devopsyolu
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Demo Web with DB Info</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .info { background: #f0f0f0; padding: 20px; border-radius: 5px; }
      </style>
    </head>
    <body>
      <h1>Demo Web Application</h1>
      <div class="info">
        <h2>Database Connection Info:</h2>
        <p><strong>DB Host:</strong> ${DB_HOST}</p>
        <p><strong>DB User:</strong> ${DB_USER}</p>
        <p><strong>DB Password:</strong> ${DB_PASS}</p>
      </div>
      <p>If you can see the values above, environment variables are working correctly!</p>
    </body>
    </html> 