pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'Build triggered by GitHub webhook!'
                script {
                    // Checkout tetikleyen branch'i dinamik olarak al
                    checkout scmGit(
                        branches: [[name: "${env.GIT_BRANCH}"]],
                        extensions: [],
                        userRemoteConfigs: [[
                            credentialsId: 'githubpat',
                            url: 'https://github.com/devopsyolu/bootcamp'
                        ]]
                    )
                }
            }
        }
    }
}
