apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: my-namespace
data:
  default.conf: | # Nginx konfigürasyonu default.conf dosyası
    server {
        listen 80;
        server_name localhost;
        
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        # Enable gzip compression
        gzip on;
        gzip_types text/plain text/css application/json application/javascript;
        
        # Add some security headers
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-XSS-Protection "1; mode=block";
    } 

    ## devopsyolu
    ## bootcamp