# PersistentVolume (PV) manifest dosyası
# Bu dosya, kalıcı depolama kaynağını tanımlar.
# PV, Kubernetes'te kalıcı depolama kaynağını temsil eder.
# PV'ler cluster düzeyinde tanımlıdır; namespace kullanılmaz.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv        # PersistentVolume adı
  # NOT: PersistentVolume'lar cluster düzeyinde tanımlıdır; namespace kullanılmaz.
spec:
  capacity:
    storage: 1Gi          # Sağlanacak depolama kapasitesi
  accessModes:
    - ReadWriteOnce       # Erişim modu
  hostPath:
    path: /mnt/data       # Minikube için yerel dosya yolu (düğümdeki yol)
  persistentVolumeReclaimPolicy: Retain  # PV kullanım sonrası ne yapacağı (saklama) 