# Secret manifest dosyası
# Bu dosya, hassas bilgileri (ör. kullanıcı adı, şifre) base64 formatında saklar.
# Secret'ler, Kubernetes'teki tüm namespace'lerde kullanılabilir.
# Secret'ler, pod'lara veya diğer kaynaklara gizli bilgileri sağlamak için kullanılır.
apiVersion: v1
kind: Secret
metadata:
  name: example-secret     # Secret'in adı
  namespace: my-namespace   # Oluşturulacağı namespace
type: Opaque
data:
  # Değerler base64 kodlu olmalıdır.
  # "admin" -> YWRtaW4=
  username: YWRtaW4=
  # "password" -> cGFzc3dvcmQ=
  password: cGFzc3dvcmQ= 