name: Pull request pipeline

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
  push:
    branches: [actions]
permissions:
  contents: read
  pull-requests: write
  issues: write
  actions: write

env:
  ENV_GENERAL: "GENEL_DEĞİŞKEN"

jobs:
  job-1:
    name: Pull request pipeline job-1
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    env:
      ENV_GENERAL: "JOB1_DEĞİŞKEN"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run-1
        run: echo "Hello ${{ env.ENV_GENERAL }}"
      - run: echo "Hello ${{ env.ENV_GENERAL }}"
      - run: |
          echo "Hello ${{ vars.VERSION }}"
          echo "Hello ${{ secrets.TOKEN }}"
      - name: Proje-1
        id: proje-1
        shell: bash
        run: |
          echo "var1=key1" >> $GITHUB_ENV
      - name: Proje-2
        run: |
          echo "${{ env.var1 }}"
      - name: Proje-3
        run: |
          echo "${{ steps.proje-1.var1 }}"

  job-2:
    name: Pull request pipeline job-2
    runs-on: devopsyolu
    if: ${{ github.event_name != 'push' }}
    needs: job-1
    environment: development
    steps:
      - name: Versiyon goster
        run: echo "Versiyon=${{ vars.VERSION }}"
      - name: Token goster
        run: echo "Token=${{ secrets.TOKEN }}"
      - name: Token goster
        run: |
          echo "Token=${{ secrets.TOKEN }}" >> token.txt
          cat token.txt
  job-3:
    name: Pull request pipeline job-3
    runs-on: self-hosted
    needs: job-2
    environment: production
    steps:
      - name: Versiyon goster
        run: echo "Versiyon=${{ vars.VERSION }}"
      - name: Token goster
        run: echo "Token=${{ secrets.TOKEN }}"
      - name: Token goster
        run: |
          echo "Token=${{ secrets.TOKEN }}" >> token.txt
          cat token.txt
  # job-4:
  #   name: Pull request pipeline job-4
  #   runs-on: self-hosted
  #   needs: [job-2, job-3]  # job-2 ve job-3 tamamlanmadan job-4 çalışmayacak
  #   steps:

